### ISSUE TITLE
Ripple,  [TimeoutError()]

### ISSUE THREAD

**Issue by RomanVarhola** [ripple/ripple-lib#1004]
Hi all. Can you help me? I have a problem with ripple-lib.
```
Ripple watcher error: [TimeoutError()]
(node:6) UnhandledPromiseRejectionWarning: TimeoutError
at Timeout.setTimeout (/app/node_modules/ripple-lib/dist/npm/common/connection.js:403:50)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
```

**Comment by intelliot** [comment]
Can you share a code snippet that reproduces this error?

When do you encounter it?

**Comment by RomanVarhola** [comment]
HI. I will provide you code. I have there problem only on server instance Ubuntu. I have got error on `getTransactions()`, so other methods work correctly. I use `node 8.11.2` and `ripple-lib: ^1.2.1`

`connection.js`
```
const { RippleAPI } = require('ripple-lib');

const api = new RippleAPI({
  server: 'wss://s1.ripple.com:443',
});

module.exports = api;
```
`main.js`

```
const rippleClient = require('../connections/xrp_wallet_rpc');

await rippleClient.connect();
const serverInfo = await rippleClient.getServerInfo();

      let completeLedgers = serverInfo.completeLedgers;
      let ledgers;

      if (completeLedgers.includes(',')) {
        completeLedgers = completeLedgers.split(',');
        const lastLedgerIndex = completeLedgers.length - 1;
        ledgers = completeLedgers[lastLedgerIndex].split('-');
      } else {
        ledgers = completeLedgers.split('-');
      }

      const minLedgerVersion = Number(ledgers[0]);
      const maxLedgerVersion = Number(ledgers[1]);

     let transactions = await rippleClient.getTransactions(account, {
        minLedgerVersion,
        maxLedgerVersion,
      });

   await rippleClient.disconnect();
```

**Comment by intelliot** [comment]
I ran your code and it worked fine. Depending on the account that you are requesting transactions for, the request can take a long time. You can try to use a smaller range of ledgers in order to get a faster response.

TimeoutError occurs when the rippled server takes too long to respond. You can add error handling with a try/catch block similar to:
```
let transactions = null
  try {
    transactions = await rippleClient.getTransactions(account, {
      minLedgerVersion,
      maxLedgerVersion
    })
  } catch (e) {
    console.log(e)
  }
```

**Comment by RomanVarhola** [comment]
Thank you very much. I have decreased range of ledgers, and all works successfully.

**Comment by intelliot** [comment]
Great! If you develop an app that you'd like to share publicly, feel free to add it to [this list of apps](https://github.com/ripple/ripple-lib/blob/develop/APPLICATIONS.md) with a PR.
