### ISSUE TITLE
preparePayment fails with NotConnectedError

### ISSUE THREAD

**Issue by dmitriano** [ripple/ripple-lib#1016]
The following code fails with NotConnectedError:

```
const api = new RippleAPI({});
api.preparePayment(fromAddress, payment, instructions).then(prepared => {});
```

the call stack is:

```
(node:4176) UnhandledPromiseRejectionWarning: NotConnectedError
warning.js:18
    at Promise (c:\repos\tradebot\wallets\xrp\node_modules\ripple-lib\dist\npm\common\connection.js:282:24)
    at new Promise (<anonymous>)
    at Connection._whenReady (c:\repos\tradebot\wallets\xrp\node_modules\ripple-lib\dist\npm\common\connection.js:280:16)
    at Connection.getLedgerVersion (c:\repos\tradebot\wallets\xrp\node_modules\ripple-lib\dist\npm\common\connection.js:293:21)
    at prepareMaxLedgerVersion (c:\repos\tradebot\wallets\xrp\node_modules\ripple-lib\dist\npm\transaction\utils.js:66:31)
    at Object.prepareTransaction (c:\repos\tradebot\wallets\xrp\node_modules\ripple-lib\dist\npm\transaction\utils.js:133:9)
    at RippleAPI.preparePayment (c:\repos\tradebot\wallets\xrp\node_modules\ripple-lib\dist\npm\transaction\payment.js:117:22)
```

but it works if I connect first like this:

```
api.connect().then(() => {
  console.log('Connected...')
  api.preparePayment(ADDRESS_1, payment, instructions).then(prepared => {
    const {signedTransaction, id} = api.sign(prepared.txJSON, SECRET_1)
    console.log(id)
    api.submit(signedTransaction).then(result => {
      console.log(JSON.stringify(result, null, 2))
      api.disconnect()
    })
  })
}).catch(console.error)
```

is not preparePayment method [offline](https://xrpl.org/rippleapi-reference.html#offline-functionality)?

**Comment by intelliot** [comment]
To prepare transactions offline, you must specify the fee, sequence, and maxLedgerVersion parameters in the transaction instructions.

https://xrpl.org/rippleapi-reference.html#transaction-instructions
