### ISSUE TITLE
ssl issue

### ISSUE THREAD

**Issue by letreset** [ripple/ripple-lib#1035]
Hi,
We are getting this ssl error when sending some transactions using wss://s1.ripple.com
How can we solve it?

> [Error: Hostname/IP doesn't match certificate's altnames: "Host: s1.ripple.com. is not in the cert's altnames: DNS:*.device42.net, DNS:device42.net"
>     at Object.checkServerIdentity (tls.js:223:17)
>     at TLSSocket.<anonymous> (_tls_wrap.js:1122:29)
>     at emitNone (events.js:106:13)
>     at TLSSocket.emit (events.js:208:7)
>     at TLSSocket._finishInit (_tls_wrap.js:643:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
>   reason: 'Host: s1.ripple.com. is not in the cert\'s altnames: DNS:*.device42.net, DNS:device42.net',
>   host: 's1.ripple.com',
>   cert:
>    { subject: { OU: [Array], CN: '*.device42.net' },
>      issuer:
>       { C: 'GB',
>         ST: 'Greater Manchester',
>         L: 'Salford',
>         O: 'COMODO CA Limited',
>         CN: 'COMODO RSA Domain Validation Secure Server CA' },
>      subjectaltname: 'DNS:*.device42.net, DNS:device42.net',
>      infoAccess: { 'CA Issuers - URI': [Array], 'OCSP - URI': [Array] },
>      modulus: 'F7E644783224B659992AEDDC931C4AB556DCE6AF1DCA6D6FEAB48B2EA44CF84FD501F4FC94B3B61A69F6C683F30B1D35D580F810DD82A392F1E68018C426BF7BFAFAE4F2D67CB24718E5CC4D138E6C6B5345F9F71FA9C4C8DE5CCA23B2448C3CB09CE7C7A7D869D5BD1EA42954324963617CF737FCEBAE1AF5CD14CEAB5D667E98E04A0EFA625B4539FDB1615720798E7623BD7F02CB14F138A35900B89A6C5A3D05355811F8081D393FF4DE10D960650D998994ED9624C98C4170B6922CE576FFEFC05353E82AFCA1593B7182288F31B87FA1F8EA3E630C8990038E0AE67A6D21460C37ABF2BC8E140293289D017DEA468208514FAEB5B8DDCC5B9B6A024F61',
>      exponent: '0x10001',
>      valid_from: 'Oct  3 00:00:00 2017 GMT',
>      valid_to: 'Oct  2 23:59:59 2020 GMT',
>      fingerprint: 'B7:2E:5C:74:1E:06:8F:21:D6:42:8B:BE:87:EF:CA:1A:36:0B:EA:14',
>      ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
>      serialNumber: '4BEEF7CF4DAA48DE9E2DFB3A6A566315',
>      raw: <Buffer 30 82 05 52 30 82 04 3a a0 03 02 01 02 02 10 4b ee f7 cf 4d aa 48 de 9e 2d fb 3a 6a 56 63 15 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 81 90 31 ... > } })]

**Comment by intelliot** [comment]
@letreset The mention of device42.net is suspicious. It seems like there's something between you and the server; for example, do you have a corporate network DNS that is putting you through a proxy?

We have verified that https://s1.ripple.com:51233/ (the WSS port) returns the correct certificate.
