### ISSUE TITLE
Test emits UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1113]
This test appears to pass, but emits an `UnhandledPromiseRejectionWarning`

```
    ✓ reconnect event on heartbeat failure (502ms)
(node:12842) UnhandledPromiseRejectionWarning: NotConnectedError: connect ECONNREFUSED 127.0.0.1:56420
    at Connection._onOpenError (/Users/user/ripple/ripple-lib/src/common/connection.ts:1:51991)
    at Object.onceWrapper (events.js:286:20)
    at WebSocket.emit (events.js:198:13)
    at ClientRequest.req.on (/Users/user/ripple/ripple-lib/node_modules/ws/lib/websocket.js:554:15)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:12842) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:12842) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by FKSRipple** [comment]
Yea, I can see this in the travis results on the original PR. That's so strange though, because when I isolate the test with `it.only()` this error doesn't happen. It looks like the mocked server isn't running on this test when you run the entire suite.
