### ISSUE TITLE
generateXAddress - Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by vanphandinh** [ripple/ripple-lib#1209]
rippleHelper.js
<img width="961" alt="Screen Shot 2020-02-14 at 10 02 40 AM" src="https://user-images.githubusercontent.com/13887599/74497818-3296bf80-4f11-11ea-86c3-5cc1fe4e3f44.png">
test.js
<img width="448" alt="Screen Shot 2020-02-14 at 10 03 49 AM" src="https://user-images.githubusercontent.com/13887599/74497861-52c67e80-4f11-11ea-8717-8a6c4f98cb78.png">

Run "node test.js"
> (node:65181) UnhandledPromiseRejectionWarning: UnexpectedError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.generateAddressAPI (/Users/vanphandinh/Desktop/projects/blockchain/node_modules/ripple-lib/dist/npm/offline/generate-address.js:29:15)
    at RippleAPI.generateXAddress (/Users/vanphandinh/Desktop/projects/blockchain/node_modules/ripple-lib/dist/npm/api.js:219:35)
    at RippleHelper.generateAddress (/Users/vanphandinh/Desktop/projects/blockchain/src/ripple2/rippleHelper.js:37:25)
    at test (/Users/vanphandinh/Desktop/projects/blockchain/src/ripple2/test.js:30:25)
    at Object.<anonymous> (/Users/vanphandinh/Desktop/projects/blockchain/src/ripple2/test.js:45:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:65181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:65181) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by intelliot** [comment]
Good catch. Thank you for reporting this. It looks like a bug introduced in ripple-lib 1.6.3. Can you try using version 1.6.2 instead?

**Comment by vanphandinh** [comment]
> Good catch. Thank you for reporting this. It looks like a bug introduced in ripple-lib 1.6.3. Can you try using version 1.6.2 instead?

Yes, thanks
