### ISSUE TITLE
Can not catch WS error

### ISSUE THREAD

**Issue by jnr101** [ripple/ripple-lib#1346]
My program sometimes loses the connection, which is expected. But sometimes it seems the error fails to be caught in the try/catch mechanism. I connect via https://xrpl.ws and have a 'try/catch' around all logical parts. Most errors are caught, but specifically ones like this are not:

```
/opt/ripple-bot/node_modules/ripple-lib/dist/npm/common/connection.js:189
            const error = new errors_1.RippledError(data.error_message || data.error, data);
                          ^

RippledError: The server is too busy to help you now.
    at RequestManager.handleResponse (/opt/ripple-bot/node_modules/ripple-lib/dist/npm/common/connection.js:189:27)
    at Connection._onMessage (/opt/ripple-bot/node_modules/ripple-lib/dist/npm/common/connection.js:281:38)
    at WebSocket.<anonymous> (/opt/ripple-bot/node_modules/ripple-lib/dist/npm/common/connection.js:356:54)
    at WebSocket.emit (node:events:376:20)
    at Receiver.receiverOnMessage (/opt/ripple-bot/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (node:events:376:20)
    at Receiver.dataMessage (/opt/ripple-bot/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/opt/ripple-bot/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/opt/ripple-bot/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/opt/ripple-bot/node_modules/ws/lib/receiver.js:77:10) {
  data: {
    error: 'tooBusy',
    error_code: 9,
    error_message: 'The server is too busy to help you now.',
    id: 10068,
    request: {
      command: 'book_offers',
      id: 10068,
      ledger_index: 'validated',
      limit: 10,
      taker: 'rxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      taker_gets: { currency: 'XRP' },
      taker_pays: { currency: 'USD', issuer: 'rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B' }
    },
    status: 'error',
    type: 'response'
  }
}
```

I use node v15.5 and ripple-lib v1.9

**Comment by elmurci** [comment]
@jnr101 are you capturing error events? Maybe you could share your code? Thanks!

```
api.on('error', (errorCode, errorMessage) => {
  //
});
```

**Comment by jnr101** [comment]
@elmurci thanks for looking into my case :-)

Maybe it's specifically that peace of code where I should take action. I had it in my code as follows:

```
function main() {

 /*****************************************************************************
  * Catch each ledger and 'do stuff'
  *****************************************************************************/

 api.on('ledger', async ledger => {
  try {
    // do stuff
  } catch(err) {
    console.error(`[${timestamp()}] Error: ${err}`)
    console.error(`[${timestamp()}] Error DATA: ${err.data}`)
    restart = true
  }
 })


 /*****************************************************************************
  * Catch errors that cannot be associated with a specific request
  *****************************************************************************/

 api.on('error', (errorCode, errorMessage, data) => {
   console.log(`[${timestamp()}] ${errorCode}: ${errorMessage}, ${data}`);
 });

 // Connnect ..

 api.connect().then(() => {
   console.log(`[${timestamp()}] Connected..`);
 }).catch(err => {
   console.error(`[${timestamp()}] Error: ${err}`)
   console.error(`[${timestamp()}] Error DATA: ${err.data}`)
   restart = true
 })

 api.on('disconnected', (code) => {
   console.error(`[${timestamp()}] Disconnected with code: ${code}`)
 })

}


/*****************************************************************************
 * Check every 3 minutes if connection is alive by checking logfiles updated
 * within 90 seconds.
 *****************************************************************************/

setInterval(function() {
  exec("echo $(( $(date +%s) - $(stat -c %Y logs/*.*_*.* | sort -u | tail -1) ))", async (err, stdout, stderr) => {
    if (err) {
      console.error('Error while executing exec ...', err)
      throw (err);
    }

    if (parseFloat(stdout) > 90 || restart === true) {
      if (restart) {
        console.log(`[${timestamp()}] Forced Restart!!`)
        restart = false
      }
      try {
        console.log(`[${timestamp()}] Timing out! Reconnecting..`)
        await api.disconnect()
        console.log(`[${timestamp()}] Disconnected..`);
        connectRippleAPI()
        main()
      } catch(err) {
        console.error(`[${timestamp()}] Error: (again) ${err}`)
        restart = true
      }
    };
  });
},  2 * 60 * 1000);

main()
```
If I would add `restart = true` to the `api.on('errror')` would that fix it? Seems logical from this perspective, even though the other functions are also encapsulated with a try/catch

**Comment by jnr101** [comment]
@elmurci , It seems I am able to catch it now with the on/error statement.
Thanks! 
I will close the issue
