### ISSUE TITLE
xAddress serialization error signing prepared txs

### ISSUE THREAD

**Issue by mrosendin** [ripple/ripple-lib#1404]
The `prepareTrustline` method creates a prepared tx that can't be signed when using an xAddress. It works with the classic address format.

**Stack trace**

```
(node:36206) UnhandledPromiseRejectionWarning: ValidationError: Serialized transaction does not match original txJSON. See `error.data`
    at checkTxSerialization (/Users/matthewrosendin/Desktop/aurei-bridge/node_modules/ripple-lib/dist/npm/transaction/sign.js:129:23)
    at signWithKeypair (/Users/matthewrosendin/Desktop/aurei-bridge/node_modules/ripple-lib/dist/npm/transaction/sign.js:62:5)
    at RippleAPI.sign (/Users/matthewrosendin/Desktop/aurei-bridge/node_modules/ripple-lib/dist/npm/transaction/sign.js:149:16)
    at Object.<anonymous> (/Users/matthewrosendin/Desktop/aurei-bridge/dist/xrpl.js:95:30)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/matthewrosendin/Desktop/aurei-bridge/dist/xrpl.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Reproduction code**

```node
const testnet = new RippleAPI({
  server: 'wss://s.altnet.rippletest.net'
});

(async api => {
  const account = api.generateXAddress({ includeClassicAddress: true })
  await api.connect();
  const trustline = {
    "currency": "USD",
    "counterparty": account.xAddress,
    "limit": "100",
    "qualityIn": 1,
    "qualityOut": 1,
    "ripplingDisabled": false,
    "frozen": false
  };
  const preparedTx = await api.prepareTrustline(accounts.receivingAccount.xAddress, trustline)
  const response = api.sign(preparedTx.txJSON, accounts.receivingAccount.secret);
})(testnet)
```

**Comment by mrosendin** [comment]
Seems to be the same problem for `prepareTransaction()`

```node
    await api.connect();
    const latestLedgerVersion = await api.getLedgerVersion()
    const preparedTx = await api.prepareTransaction({
        "TransactionType": "Payment",
        "Account": accounts.receivingAccount.classicAddress,
        "Amount": {
          "currency": "AUR",
          "value": amount.toString(),
          "issuer": accounts.issuingAccount.classicAddress
        },
        "Destination": accounts.receivingAccount.classicAddress,
        LastLedgerSequence: latestLedgerVersion + 15
    })
    const maxLedgerVersion = preparedTx.instructions.maxLedgerVersion
    const response = api.sign(preparedTx.txJSON, accounts.issuingAccount.secret);
    const txID = response.id
    const txBlob = response.signedTransaction
    const result = await api.submit(txBlob);
    const earliestLedgerVersion = latestLedgerVersion + 1;
    await api.disconnect()
    await api.disconnect()
    return await validateTransaction(txID, earliestLedgerVersion, maxLedgerVersion!)
```

I noticed that `prepareSettings` does not seem to have this problem.
