### ISSUE TITLE
Orderbook unhandled null comparison exception

### ISSUE THREAD

**Issue by kureus** [ripple/ripple-lib#336]
ripple-lib version - 0.12.2

```
/src/node_modules/ripple-lib/src/js/ripple/orderbook.js:630
  offer.is_fully_funded = fundedAmount.compareTo(currentOfferSum) >= 0;
                                       ^
TypeError: Cannot call method 'compareTo' of undefined
    at OrderBook.setOfferFundedAmount (/src/node_modules/ripple-lib/src/js/ripple/orderbook.js:630:40)
    at /src/node_modules/ripple-lib/src/js/ripple/orderbook.js:804:10
    at arrayEach (/src/node_modules/ripple-lib/node_modules/lodash/index.js:1342:13)
    at Function. (/src/node_modules/ripple-lib/node_modules/lodash/index.js:3299:13)
    at OrderBook.updateOwnerOffersFundedAmount (/src/node_modules/ripple-lib/src/js/ripple/orderbook.js:789:5)
    at OrderBook.modifyOffer (/src/node_modules/ripple-lib/src/js/ripple/orderbook.js:1015:8)
    at handleNode (/src/node_modules/ripple-lib/src/js/ripple/orderbook.js:876:14)
    at arrayEach (/src/node_modules/ripple-lib/node_modules/lodash/index.js:1342:13)
    at Function. (/src/node_modules/ripple-lib/node_modules/lodash/index.js:3299:13)
    at OrderBook.notify (/src/node_modules/ripple-lib/src/js/ripple/orderbook.js:894:5)
```

**Comment by boxbag** [comment]
what are the taker gets and taker pays currencies?

**Comment by kureus** [comment]
USD.Bitstamp/USD.Snapswap
