### ISSUE TITLE
AssertionError: Offer total cannot be negative

### ISSUE THREAD

**Issue by gilduz** [ripple/ripple-lib#352]
Hello everyone,

I'm trying to receive offers updates for n markets using this code

```javascript
function requestAllBooks(markets, remote) {
    for (var i = 0; i < markets.length; i++) {
        for (var j = 0; j < markets.length; j++) {
            if (i!=j) {
                var book = remote.book(markets[i].currency, markets[i].issuer, markets[j].currency, markets[j].issuer);
                book.on("model", handle_book);
                book.on('offer_funds_changed', handle_book_funds);
            }
        }
    }
```

When i send the requests I've got this warning:

_[2015-05-23T15:11:31.183Z] remote: DEPRECATED: First argument to request constructor should be an object containing request properties -- at Remote.book.Remote.createOrderBook (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/src/js/ripple/remote.js:2021:9)_

However everything seems works, until I've got this error (this happen randomly):

_AssertionError: Offer total cannot be negative
    at OrderBook.subtractOwnezrOfferTotal (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/src/js/ripple/orderbook.js:485:3)
    at OrderBook.deleteOffer (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/src/js/ripple/orderbook.js:1039:12)
    at handleNode (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/src/js/ripple/orderbook.js:866:14)
    at arrayEach (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/node_modules/lodash/index.js:1361:13)
    at Function.<anonymous> (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/node_modules/lodash/index.js:3405:13)
    at OrderBook.notify (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/src/js/ripple/orderbook.js:894:5)
    at Remote.<anonymous> (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/src/js/ripple/remote.js:648:27)
    at Array.forEach (native)
    at Remote._handleTransaction (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/src/js/ripple/remote.js:646:38)
    at Remote._handleMessage (/Users/myName/Dropbox/Ripple/node_modules/ripple-lib/src/js/ripple/remote.js:542:12)_

Do you have some tips to fix the problem? I'm using the last npm version of ripple-lib

Thanks! :)

**Comment by clark800** [comment]
I was able to reproduce this bug with the following code running on the HEAD of develop after fixing another bug.

Prerequisite bugfix:
https://github.com/ripple/ripple-lib/pull/353

Code to reproduce:
https://gist.github.com/clark800/f5e095a7f5e86b242193

Output with trace enabled:
https://gist.github.com/clark800/265e01d057bf751c38c9

It took about 20 minutes for the error to appear. I haven't found the source of this issue yet.

**Comment by gilduz** [comment]
Yes, same problem here, after 20 minutes more or less the error appears
