### ISSUE TITLE
Websocket closing

### ISSUE THREAD

**Issue by tuloski** [ripple/ripple-lib#749]
It has been a week or two that the websocket fails and ripple-lib (old verison 0.12.6) trows an error:

 
/home/odroid/node_modules/ripple-lib/node_modules/ws/lib/WebSocket.js:214
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/home/odroid/node_modules/ripple-lib/node_modules/ws/lib/WebSocket.js:214:16)
    at Server._sendMessage (/home/odroid/node_modules/ripple-lib/dist/npm/server.js:746:14)
    at sendRequest (/home/odroid/node_modules/ripple-lib/dist/npm/server.js:781:10)
    at Server._request (/home/odroid/node_modules/ripple-lib/dist/npm/server.js:788:5)
    at Remote.request (/home/odroid/node_modules/ripple-lib/dist/npm/remote.js:745:12)
    at Request.request (/home/odroid/node_modules/ripple-lib/dist/npm/request.js:59:17)
    at Request.callback (/home/odroid/node_modules/ripple-lib/dist/npm/request.js:218:8)
    at Remote.requestBookOffers (/home/odroid/node_modules/ripple-lib/dist/npm/remote.js:1650:11)

 

Was there some modification at rippled that can influence this? Or more traffic on Ripple's public servers? Because before it was happening once every week or a few days, now every 0.5/2 hours. I don't think it is ripple-lib related.
Topic on XRPtalk: https://www.xrpchat.com/topic/3341-websocket-closing-ripple-lib/

Even if not ripple-lib related, a way to reconnect automatically when the ws closes would be nice.

**Comment by donovanhide** [comment]
See https://github.com/ripple/rippled/issues/2026

**Comment by miguelportilla** [comment]
This [pull request](https://github.com/ripple/rippled/pull/2067) fixes the websocket disconnect issue.

**Comment by intelliot** [comment]
Looks like this has been fixed. Feel free to open a new issue if the problem recurs.
