### ISSUE TITLE
ELIFECYCLE error when running npm install

### ISSUE THREAD

**Issue by jason4zhu** [ripple/ripple-lib#796]
Hi,

I tried to `git clone` the repo and run `npm install` under it but it complains the following error:

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> fsevents@1.1.2 install /Users/jasonzhu/rippleWallet/ripple-lib/node_modules/fsevents
> node install

[fsevents] Success: "/Users/jasonzhu/rippleWallet/ripple-lib/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> sauce-connect-launcher@0.14.0 postinstall /Users/jasonzhu/rippleWallet/ripple-lib/node_modules/sauce-connect-launcher
> node scripts/install.js

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> ripple-lib@0.17.7 prepublish /Users/jasonzhu/rippleWallet/ripple-lib
> npm run clean && npm run compile


> ripple-lib@0.17.7 clean /Users/jasonzhu/rippleWallet/ripple-lib
> rm -rf dist/npm && rm -rf build/flow


> ripple-lib@0.17.7 compile /Users/jasonzhu/rippleWallet/ripple-lib
> babel -D --optional runtime -d dist/npm/ src/

module.js:442
    throw err;
    ^

Error: Cannot find module 'lodash/kebabCase'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jasonzhu/rippleWallet/ripple-lib/node_modules/babel-cli/lib/babel/index.js:12:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ripple-lib@0.17.7 compile: `babel -D --optional runtime -d dist/npm/ src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ripple-lib@0.17.7 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jasonzhu/.npm/_logs/2017-09-09T15_49_04_783Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ripple-lib@0.17.7 prepublish: `npm run clean && npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ripple-lib@0.17.7 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jasonzhu/.npm/_logs/2017-09-09T15_49_04_882Z-debug.log
```

Any suggestions? Thanks!

Node: v6.3.0
npm: 5.4.1
OS: mac osx 10.11.6

**Comment by intelliot** [comment]
@jason4zhu This should be resolved in the current version of ripple-lib, which uses an updated version of lodash. Please let us know if the problem persists. Thanks!
