### ISSUE TITLE
Allow lowercase hexadecimal (DEVX-87)

### ISSUE THREAD

**Issue by passionofvc** [ripple/ripple-lib#967]
**Can't sign memos with lowercase hexadecimal**

sign api not work with memos input when sign transaction.
the same worked when sign by rippled.

Name | Type | Description
-- | -- | --
txJSON | string | Transaction represented as a JSON string in rippled format.

[transaction-memos](https://developers.ripple.com/rippleapi-reference.html#transaction-memos)

```
#test-sign-with-memo.js 
onst RippleAPI = require("ripple-lib").RippleAPI;
const api = new RippleAPI({server:'wss://localhost:8080'});

//payment
 const payTxJson = {
     "Flags"             : "2147483648",
     "TransactionType"   : "Payment",
     "Account"           : "rwiZ3q3D3QuG4Ga2HyGdq3kPKJRGctVG8a",
     "Amount"            : "10000000",
     "LastLedgerSequence": 14000999,
     "Destination"       : "rUeEBYXHo8vF86Rqir3zWGRQ84W9efdAQd",
     "Fee"               : "12",
     "Sequence"          : 12,
     "SourceTag"         : 8888,
     "DestinationTag"    : 9999,
     "Memos"             : [
      {
          "Memo": {
              "MemoType" :"687474703a2f2f6578616d706c652e636f6d2f6d656d6f2f67656e65726963",
              "MemoData" :"72656e74"
          }
      }
     ]
 }
 
 secret='shd2nxpFD6iBRKWsRss2P4tKMWyy9'
 tx_params= JSON.stringify(payTxJson)
 var raw_tx = api.sign(tx_params, secret);
 
```
$ node test-sign-with-memo.js 
/home/ripple/ripple-lib/node_modules/ripple-binary-codec/distrib/npm/utils/bytes-utils.js:38
    throw new Error('`' + hex + '` is not a valid hex representation of a byte');
    ^

Error: `6e` is not a valid hex representation of a byte
    at byteForHex (/home/ripple/ripple-lib/node_modules/ripple-binary-codec/distrib/npm/utils/bytes-utils.js:38:11)
    at parseBytes (/home/ripple/ripple-lib/node_modules/ripple-binary-codec/distrib/npm/utils/bytes-utils.js:52:18)
    at new Blob (/home/ripple/ripple-lib/node_modules/ripple-binary-codec/distrib/npm/types/blob.js:9:21)
    at Function.from (/home/ripple/ripple-lib/node_modules/ripple-binary-codec/distrib/npm/types/blob.js:22:14)
    at /home/ripple/ripple-lib/node_modules/ripple-binary-codec/distrib/npm/types/st-object.js:31:46
    at /home/ripple/ripple-lib/node_modules/lodash/lodash.js:13807:16
    at /home/ripple/ripple-lib/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/home/ripple/ripple-lib/node_modules/lodash/lodash.js:2996:24)
    at Function.transform (/home/ripple/ripple-lib/node_modules/lodash/lodash.js:13806:43)
    at Function.from (/home/ripple/ripple-lib/node_modules/ripple-binary-codec/distrib/npm/types/st-object.js:28:18)

```
#version
ripple-lib
└─┬ ripple-lib@1.1.0
  ├─┬ ripple-lib-
```

```
host_url=http://127.0.0.1:5005
 curl -s  -X POST "$host_url" -d @- <<-END
 {
     "method" : "sign",
     "params" : [
      {
          "secret" : "shd2nxpFD6iBRKWsRss2P4tKMWyy9",
          "tx_json" : {
              "TransactionType":"Payment",
              "Account":"rwiZ3q3D3QuG4Ga2HyGdq3kPKJRGctVG8a",
              "Amount":"10000000",
              "Fee":"12",
              "Destination":"rUeEBYXHo8vF86Rqir3zWGRQ84W9efdAQd",
              "Sequence":"12",
              "SourceTag": 8888,
              "DestinationTag": 9999,
              "Memos" : [
               {
                 "Memo": {
                     "MemoType" :"687474703a2f2f6578616d706c652e636f6d2f6d656d6f2f67656e65726963",
                     "MemoData" :"72656e74"
                 }
               }
             ]
         },
         "offline": "false"
     }
    ]
 }
 END


{
  "result": {
    "status": "success",
    "tx_blob": "120000228000000023000022B8240000000C2E0000270F61400000000098968068400000000000000C73210305E09ED602D40AB1AF65646A4007C2DAC17CB6CDACDE301E74FB2D728EA057CF744630440220463DAC2268E84988657E982AE94F9C37A1F349F051E258035147958DF1F6498802206E1DBA818301705BE98A62A83834AB0BB9E2BBA0389D88E4174043108BF39E9F81146C1856D0E36019EA75C56D7E8CBA6E35F9B3F71583147FB49CD110A1C46838788CD12764E3B0F837E0DDF9EA7C1F687474703A2F2F6578616D706C652E636F6D2F6D656D6F2F67656E657269637D0472656E74E1F1",
    "tx_json": {
      "Account": "rwiZ3q3D3QuG4Ga2HyGdq3kPKJRGctVG8a",
      "Amount": "10000000",
      "Destination": "rUeEBYXHo8vF86Rqir3zWGRQ84W9efdAQd",
      "DestinationTag": 9999,
      "Fee": "12",
      "Flags": 2147483648,
      "Memos": [
        {
          "Memo": {
            "MemoData": "72656E74",
            "MemoType": "687474703A2F2F6578616D706C652E636F6D2F6D656D6F2F67656E65726963"
          }
        }
      ],
      "Sequence": 12,
      "SigningPubKey": "0305E09ED602D40AB1AF65646A4007C2DAC17CB6CDACDE301E74FB2D728EA057CF",
      "SourceTag": 8888,
      "TransactionType": "Payment",
      "TxnSignature": "30440220463DAC2268E84988657E982AE94F9C37A1F349F051E258035147958DF1F6498802206E1DBA818301705BE98A62A83834AB0BB9E2BBA0389D88E4174043108BF39E9F",
      "hash": "1D3139D5EF66F23D0A55992C89F9E4625712A783310F0630CC7049E5E5282FE0"
    }
  }
}

```

**Comment by sublimator** [comment]
Try 6E, not 6e

**Comment by carterbrett** [comment]
@sublimator Thanks for the tip. Had the same issue and converting to uppercase did the trick!

**Comment by RareData** [comment]
+1 to make all hexadecimal strings case-insensitive.
